root: true

env:
  browser: true
  node: true

parser: vue-eslint-parser

parserOptions:
  parser: '@typescript-eslint/parser'
  sourceType: module

extends:
    - '@nuxtjs/eslint-config-typescript'
    - 'plugin:@typescript-eslint/recommended'
    - plugin:jest/recommended
    - plugin:prettier/recommended
    - prettier
    - prettier/vue

plugins:
  - vue

rules:
  no-console: off
  no-debugger: off
  semi:
    - error
    - always
  camelcase:
    - error
    - allow:
      - created_at
      - updated_at
      - client_id
      - client_secret
  vue/max-attributes-per-line: off
  new-cap: off
  prettier/prettier:
    - error
    -
      singleQuote: true
      trailingComma: es5
      semi: true
      jsxBracketSameLine: true
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-this-alias':
    - error
    - allowedNames:
      - self
  '@typescript-eslint/no-unused-vars':
    - error
    -
      argsIgnorePattern: __
