version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  test:
    docker:
      - image: circleci/node:lts
      - image: circleci/mongo:latest
    steps:
      - checkout
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - run:
          name: Send Coverage Repo
          command: cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
      - run:
          name: Remove Local Repo
          command: rm -rf ./coverage

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
