version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:latest
  environment:
    NODE_ENV: test
    NODE_OPTIONS: --max_old_space_size=4096

jobs:
  # Install
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  # Lint
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Lint
          command: yarn lint --format junit -o reports/eslint-results.xml
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports

  # Test
  test:
    <<: *defaults
    docker:
      - image: circleci/node:latest
      - image: circleci/mongo:latest
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Test
          command: yarn test --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "reports/jest-results.xml"
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - run:
          name: Send Coverage Repo
          command: yarn codecov

workflows:
  version: 2
  install_and_test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - lint
