version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/mongo:latest
  environment:
    NODE_ENV: test
    NODE_OPTIONS: --max_old_space_size=4096

jobs:
  # Install
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --non-interactive
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  # Lint
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Lint
          command: yarn lint

  # Test
  test:
    <<: *defaults
    docker:
      - image: circleci/mongo:latest
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Test
          command: yarn test
      - run:
          name: Send Coverage Repo
          command: cat coverage/lcov.info | node_modules/.bin/coveralls

workflows:
  version: 2
  install_and_test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - lint
